# apps/your-app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bufferpost-backend
  namespace: bufferpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bufferpost-backend
  template:
    metadata:
      labels:
        app: bufferpost-backend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      automountServiceAccountToken: false
      containers:
      - name: bufferpost-backend
        image: abuobaid/bufferpost-backend-140lnp:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: app-secrets

        # Just give it more time to start - that's it!
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 20  
          
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "200m"
            ephemeral-storage: "2Gi"