#ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: bufferpost
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-bufferpost.systrox.com
    secretName: bufferpost-tls      # cert-manager will auto-create this secret
  rules:
  - host: api-bufferpost.systrox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bufferpost-backend-service
            port:
              number: 80