apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: bufferpost
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: "letsencrypt-staging"  # Switch to "letsencrypt-prod" when ready
    haproxy.org/ssl-redirect: "true"
    haproxy.org/server-ssl: "false"
    haproxy.org/timeout-server: "60s"
    haproxy.org/timeout-client: "60s"
spec:
  tls:
  - hosts:
    - api-bufferpost.systrox.com
    - app.example.com
    - admin.example.com
    secretName: example-com-tls      # cert-manager will auto-create this secret
  rules:
  - host: api-bufferpost.systrox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bufferpost-backend-service
            port:
              number: 80